apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    name: ''
    namespace: metallb-system
    server: https://kubernetes.default.svc
  source:
    path: yaml
    repoURL: https://github.com/azarkawi/metallb.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true