apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: metallb-system
  name: controller
  labels:
    app: metallb
    component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
      component: controller
  template:
    metadata:
      labels:
        app: metallb
        component: controller
    spec:
      containers:
      - name: controller
        image: quay.io/metallb/controller:v0.14.8
        args: ["--port=7472"]
        ports:
        - containerPort: 7472
          name: metrics
        securityContext:
          allowPrivilegeEscalation: false
        resources: 
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"