apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: metallb-system
  name: speaker
  labels:
    app: metallb
    component: speaker
spec:
  selector:
    matchLabels:
      app: metallb
      component: speaker
  template:
    metadata:
      labels:
        app: metallb
        component: speaker
    spec:
      containers:
      - name: speaker
        image: quay.io/metallb/speaker:v0.14.8
        ports:
        - name: metrics
          containerPort: 7472
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"