apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: metallb-system
  name: speaker
spec:
  selector:
    matchLabels:
      app: metallb
      component: speaker
  template:
    metadata:
      labels:
        app: metallb
        component: speaker
    spec:
      containers:
      - name: speaker
        image: quay.io/metallb/speaker:v0.14.8
        args: ["--port=7472"]
        ports:
        - containerPort: 7472
        securityContext:
          allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - effect: NoSchedule
        key: "node-role.kubernetes.io/master"
        operator: Exists