# ServiceAccount voor de MetalLB controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-controller
  namespace: metallb-system
---
# ClusterRole voor de MetalLB controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-controller
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods", "namespaces", "configmaps"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
# ClusterRoleBinding voor de MetalLB controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-controller-binding
subjects:
  - kind: ServiceAccount
    name: metallb-controller
    namespace: metallb-system
roleRef:
  kind: ClusterRole
  name: metallb-controller
  apiGroup: rbac.authorization.k8s.io
